version: "3"

services:
  app:
    build: ./containers/app/
    env_file: .env.development
    command: sh ./containers/app/start.sh
    volumes:
      - bundle-store:/usr/local/bundle
      - .:/usr/src
    ports:
      - 3000:3000
      - 3035:3035
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    build: ./containers/db/
    env_file: .env.development
    volumes:
      - db-store:/usr/local/var/postgres
    ports:
      - 5432:5432

volumes:
  db-store:
  bundle-store: