version: "3"

services:
  app:
    build: ./containers/app/
    command: sh ./containers/app/start.sh
    volumes:
      - bundle-store:/usr/local/bundle
      - .:/usr/src
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
    env_file: .env.development
    tty: true
    stdin_open: true

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env.development
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-store:
  bundle-store: