default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("POSTGRES_USER", "dev") %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", "password") %>
  host: <%= ENV.fetch("POSTGRES_HOST", "db") %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", "dev_db") %>

test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_TEST_DATABASE", "test_db") %>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DATABASE"] %>
  reconnect: true